name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install flask textblob

      - name: Run Lint Check (Basic)
        run: |
          python -m py_compile app.py

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          fonhope: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          docker build -t fonhope/sentiment-api:latest .
          docker push fonhope/sentiment-api:latest
